name: Manual Build

on:
  # Allows manual triggering from the Actions tab
  workflow_dispatch:
    # Optional: Add custom inputs (like environment or version)
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget zipalign apksigner

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin' # Popular, well-supported OpenJDK distribution

      - name: Modify and Rebuild APK
        run: |
          # Download latest Brave
          chmod +x ./download_latest_brave.sh
          ./download_latest_brave.sh

          # 1. Decompile
          java -jar apktool_3.0.1.jar d Bravearm64Universal.apk -o Bravearm64Universal
          
          # 2. Update Package Name (Manifest + Smali paths)
          sed -i 's/package="com.brave.browser_nightly"/package="com.microsoft.emmx"/g' Bravearm64Universal/AndroidManifest.xml
          echo "renameManifestPackage: com.microsoft.emmx" >> Bravearm64Universal/apktool.yml
          grep -rl "Lcom/brave/browser_nightly" Bravearm64Universal/ --include="*.smali" | xargs -r sed -i "s|Lcom/brave/browser_nightly|Lcom/microsoft/emmx|g"
          
          # 3. Rebuild
          java -jar apktool.jar b Bravearm64Universal -o unsigned.apk

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.jks

      - name: Sign APK
        run: |
          zipalign -v 4 unsigned.apk aligned.apk
          apksigner sign \
            --ks release.jks --ks-pass pass:${{ secrets.KEY_PASSWORD }} \
            --key-pass pass:${{ secrets.KEY_PASSWORD }} --ks-key-alias ${{ secrets.KEY_ALIAS }} \
            --out final_app.apk aligned.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Bravearm64Universal-emmx-$(date +%F).apk
          path: final_app.apk


